- name: Install llmfit
  homebrew:
    name: AlexsJones/llmfit/llmfit
    state: present
  tags:
    - "ai"

- name: Install ollama
  homebrew:
    name: ollama
    state: present
  tags:
    - "ai"

- name: Install openwebui
  command: docker run -d -p 3000:8080 -e 'OLLAMA_BASE_URL=http://host.docker.internal:11434' -e 'WEBUI_AUTH=False' -v open-webui:/app/backend/data --rm --name open-webui ghcr.io/open-webui/open-webui:main
  tags:
    - "ai"

# - name: Install opencode
#   homebrew:
#     name: opencode
#     state: present
#   tags:
#     - "ai"
