- name: Install Docker CLI
  community.general.homebrew:
    name: docker
    state: present
  tags:
    - "docker"

- name: Install Docker Compose
  community.general.homebrew:
    name: docker-compose
    state: present
  tags:
    - "docker"

- name: Install Docker Desktop
  community.general.homebrew_cask:
    name: docker
    state: present
  tags:
    - "docker"
