- name: Set git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ lookup('env', 'GIT_USER_NAME') }}"
  when: lookup('env', 'GIT_USER_NAME') | length > 0
  tags:
    - "git"
- name: Set git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ lookup('env', 'GIT_USER_EMAIL') }}"
  when: lookup('env', 'GIT_USER_EMAIL') | length > 0
  tags:
    - "git"
- name: Install Git command-line tools
  community.general.homebrew:
    name:
      - git-delta
      - lazygit
    state: present
  tags:
    - "git"
- name: Configure global Git defaults
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - name: core.pager
      value: delta
    - name: interactive.diffFilter
      value: delta --color-only
    - name: delta.features
      value: tokyonight
    - name: delta.tokyonight.dark
      value: "true"
    - name: delta.tokyonight.minus-style
      value: "syntax #3b2a3c"
    - name: delta.tokyonight.minus-emph-style
      value: "syntax #f7768e bold ul"
    - name: delta.tokyonight.plus-style
      value: "syntax #243b36"
    - name: delta.tokyonight.plus-emph-style
      value: "syntax #9ece6a bold ul"
    - name: delta.tokyonight.zero-style
      value: "syntax #565f89"
    - name: delta.tokyonight.file-style
      value: "bold #7aa2f7"
    - name: delta.tokyonight.hunk-header-style
      value: file line-number syntax
    - name: delta.tokyonight.line-numbers
      value: "true"
    - name: delta.tokyonight.line-numbers-minus-style
      value: "#f7768e"
    - name: delta.tokyonight.line-numbers-plus-style
      value: "#9ece6a"
    - name: delta.tokyonight.line-numbers-zero-style
      value: "#565f89"
    - name: diff.algorithm
      value: histogram
    - name: pull.rebase
      value: "true"
    - name: rerere.enabled
      value: "true"
    - name: rerere.autoupdate
      value: "true"
  tags:
    - "git"
